### PR TITLE
Switch to adoptopenjdk 11 base image

### PR DESCRIPTION
**Pull request by timja**
This image is multiarch compatible, I can build it locally and then use the core-pr-tester fine

Getting a multiarch image working in CI seems to be an absolute nightmare though =/

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
+1, we definitely need to migrate the entire Docker ecosystem

**Comment by timja** [comment]
@oleg-nenashev can you grant myself (timja is username there too) and jenkinsinfraadmin access to core-pr-tester on docker hub. I’m playing around with multi arch builds and if I can get it working I’ll change this to publish from CI

**Comment by oleg-nenashev** [comment]
@timja done

**Comment by timja** [comment]
@oleg-nenashev are you able to disable the docker hub auto build for this repo? 

https://hub.docker.com/repository/docker/jenkins/core-pr-tester/builds

I get errors in the console when I try (typical docker hub...)

**Pull request merged**
