### PR TITLE
Use Apache Maven 3.6.3

### PR DESCRIPTION
**Pull request by MarkEWaite**
Excuse to also update the image to cache more recent components.

### CODE REVIEW

**Comment by timja** [comment]
@batmat

**Comment by timja** [comment]
@batmat do you want anyone else's help on this repo? 

I use this quite regularly and would be able to help out...

**Comment by batmat** [comment]
Yes, definitely. I'm clearly not doing a good job. I'm happy to share or hand over maintainership to you if you would like to.

**Comment by timja** [comment]
> Yes, definitely. I'm clearly not doing a good job. I'm happy to share or hand over maintainership to you if you would like to.

Thanks I've added myself to the repo.

I've got a PR coming soon-ish hopefully for a multi-arch build.

(I'm running on Mac M1, and the current build seg faults on the preview doc through rosetta emulation, but if I build it locally with some tweaks it works great)

**Pull request merged**
